services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: order-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    container_name: order-redis
    ports:
      - "6379:6379"